### PR TITLE
Remove Local Cache of Mapping

### PR DESCRIPTION
**Pull request by JSponaugle**
Removed Local Cache of Mapping to prevent any issues with On Chain OPCode Created Mappings.

### CODE REVIEW

**Comment by Cryptarchist** [comment]
@JSponaugle after some thought I'm not sure this will work.

With blocks mined every 60 seconds, inside any given 60 second window we could post more than 1 new team, sport or league.

Without the caching in place an Oracle Node would post Team A with ID 1 and Team B with ID 1 to the same block, but only one of these team names can be assigned to ID 1. So one team would fail silently.

The current situation isn't ideal and needs tweaking to work for a decentralised Oracle Network, but for this point in time where the Oracle Node is controlled by the Wagerr team I think the caching will have a less likely occurrence of an ID clash or some other bad data event than removing the caching all together.

**Comment by JSponaugle** [comment]
Overall the assigning of a ID should be done via the network. Where a Oracle Node does not send in a assignment ID but the Network it self just adds the items to the next iteration in the local db. This will allow multi names to be posted without issue.

**Comment by Cryptarchist** [comment]
@JSponaugle 👍 to that, will look into that for the next/a future release.

**Comment by Kokary** [comment]
No longer relevant

**Pull request closed without merging**
