### PR TITLE
Hardcoded seeds update pre-2.0.1 branch

### PR DESCRIPTION
**Pull request by Cryptarchist**

### CODE REVIEW

**Review by Kokary — COMMENTED** [review]
There's a TODO-type of comment in https://github.com/wagerr/wagerr/blob/d647483654a84ac7217f519bc537acac11971c1c/contrib/seeds/README.md
`Speak to Cryptarchist about getting a dump of the dnsseed.dump data into a seeds_main.txt file.`

Is this intentional?

**Comment by Kokary** [comment]
A really dirty way to get a list of peers from a local node would be `getpeerinfo|grep addr\"|cut -d'"' -f4`

**Comment by Cryptarchist** [comment]
@Kokary yes intentional for now. I am going to make it so anyone can pull the DNS seed dump from the server using `curl`, but don't have it ready right now.

The DNS seed is the best place to get a full list of IPs to randomly choose from to hardcode as it stores a more complete dump of IPs it finds on the network.

For example a Bitcoin DNS seed dump I pulled today contains >450,000 IPs, which isn't possible to pull that many from the client.

This means we lessen the chance of using suspicious IPs or hardcoding the same IPs over and over and instead rotating them from a more complete pool.

**Review by Kokary — APPROVED** [review]
OK, makes sense.

ACK

**Pull request merged**
