### PR TITLE
LevelDB 1.18

### PR DESCRIPTION
**Pull request by Cryptarchist**
Convert `leveldb` into a subtree.

Assists with cleaning up the missing `.gitignore` file and erroneous `build_config.mk` file, plus easier to manage future LevelDB updates.

### CODE REVIEW

**Comment by WagerrTor** [comment]
there are conflicts, can you look at it and pull again?

**Comment by mitchellcash** [comment]
@WagerrTor which conflicts?

The `build_config.mk` file shouldn't be in the repo and it was missing the `.gitignore` file so I have added that back from upstream.

**Comment by WagerrTor** [comment]
grafik

**Comment by Cryptarchist** [comment]
@WagerrTor strange, it might be something to do with it being a subtree.

I have cleaned the commit up a bit and rebased ontop of master.

I also ran a check against `git-subtree-check.sh`:
```
$ bash contrib/devtools/git-subtree-check.sh src/leveldb
src/leveldb in HEAD currently refers to tree 38c7397c5aad9ef6ecbc1fb6fd7b6e5fa862c57d
src/leveldb in HEAD was last updated in commit f5e3dc2444ffc88377377f9f1d2e0b5e3014e6db (tree 38c7397c5aad9ef6ecbc1fb6fd7b6e5fa862c57d)
src/leveldb in HEAD was last updated to upstream commit 69d38792c87addc44eef4f33c866004ebdced4a5 (tree 38c7397c5aad9ef6ecbc1fb6fd7b6e5fa862c57d)
GOOD
```

Hopefully it's good now 😃

**Comment by WagerrTor** [comment]
sadly not :( 
grafik

I would suggest to create new pull and we close this one.

**Pull request merged**
