### PR TITLE
Disable buttons to accidentally burn coins

### PR DESCRIPTION
**Pull request by trappist**
Instead of issuing a warning.

### CODE REVIEW

**Review by Cryptarchist — APPROVED** [review]
@trappist awesome work! GUI looks much nicer.



Also thanks for cleaning up some of the duplicate layout names, I've been meaning to do that.

ACK 07461f56f1c92a6cc3ae1d8044be12bc5b21e963 & 14665bfb119af276d4d55de32dec1f5bfff9c49d

**Comment by ckti** [comment]
Looks Brilliant!

**Comment by trappist** [comment]
> Also thanks for cleaning up some of the duplicate layout names

I'm not too familiar with C++ or QT, but I was getting build warnings until I did that, after I removed the "don't bet on n/a odds" warning.

**Review by Kokary — APPROVED** [review]
Very nice, thanks!
Tested; ACK.

**Pull request merged**
