### PR TITLE
2019 regtest mode and fake test suite

### PR DESCRIPTION
**Pull request by WagerrTor**

### CODE REVIEW

**Review by Kokary — APPROVED** [review]
I was able to construct a zWGR V1 spend with this PR, and all else looks good to me, so ACK here.

**Review by ckti — APPROVED** [review]
WIll be able to get the test scripts up and running once regtest chain is working fully. Pull looks good have cloned, compiled and run this fork with no issues.

**Comment by WagerrTor** [comment]
Second batch of fixes pushed.

Thanks @Kokary for confirmation, as that part was cleaned up, good that it works now.

@ckti please test those scripts now, they are updated

**Comment by ckti** [comment]
getting "Arguments: ("error('unpack requires a bytes object of length 8',)",)" from zerocoin_wrapped_serials, p2p_pos_fakestake, and p2p_pos_fakestake_accepted and erroring out with Couldn't create new block (code -32603) on other tests
this happens no matter which branch or repo i use

**Pull request closed without merging**
